### ISSUE TITLE
大神，能在国内期货市场跑一跑吗？

### ISSUE THREAD

**Issue by xinjin9999** [Vespa314/chan.py#10]

**Comment by Vespa314** [comment]
没研究过这个，如果知道数据可以怎么获取，理论上是一样可以跑的；

**Comment by xinjin9999** [comment]
我是国内券商做投资交易的，数据可以搞到。
能否方便加一下微信，我学缠论也好几年了，看到你的项目文档感觉很牛，佩服佩服。最近正在啃你的代码。
不知能不能加入团队一起研究，看看我能不能贡献点力量
















在 2023-01-28 15:49:18，"Vespa314" ***@***.***> 写道：

没研究过这个，如果知道数据可以怎么获取，理论上是一样可以跑的；

**Comment by Vespa314** [comment]
可以一起讨论学习，微信号发我邮箱吧。

**Comment by xinjin9999** [comment]
微信号：jinxin800646
金鑫
















在 2023-02-07 15:11:39，"Vespa314" ***@***.***> 写道：

可以一起讨论学习，微信号发我邮箱吧。

**Comment by Vespa314** [comment]
没搜到。

**Comment by xinjin9999** [comment]
不好意思
我发现微信号添加的没有打开哈哈
刚刚打开，或者手机号吧 13911760944
















在 2023-02-07 18:30:06，"Vespa314" ***@***.***> 写道：

没搜到。

**Comment by xinjin9999** [comment]
大神，你有没有听说过国外有一个叫Demark的指标，具体的是TD序列（下图）
















在 2023-02-07 18:30:06，"Vespa314" ***@***.***> 写道：

没搜到。
