### ISSUE TITLE
web端页面

### ISSUE THREAD

**Issue by Vespa314** [Vespa314/chan.py#16]
为了方便体验和调试，不知道有没有前端大佬想一起来开发个页面工具？

后端功能基本是具备的。

**Comment by robinchen** [comment]
前端咱也是半桶水..

**Comment by robinchen** [comment]
听说有个TradingView相当好用， 你可以试试

**Comment by Vespa314** [comment]
> 听说有个TradingView相当好用， 你可以试试

嗯，这个我知道；能上TV当然是个不错的选择；

但是我自己下游有太多自定义的模型和交易相关的操作了，所以后端选择python自己开发自由度比较大；

python开发的代码转到TV上，代码的迁移成本无异于重做；

而TV对接python后端这块的实现和资料比较少；还没弄懂可以怎么搞，好像也是要部署一个本地化的TV SDK？

**Comment by robinchen** [comment]
好像是的， 需要部署一个本地化

**Comment by topsoftbj** [comment]
> 



> > 听说有个TradingView相当好用， 你可以试试
> 
> 嗯，这个我知道；能上TV当然是个不错的选择；
> 
> 但是我自己下游有太多自定义的模型和交易相关的操作了，所以后端选择python自己开发自由度比较大；
> 
> python开发的代码转到TV上，代码的迁移成本无异于重做；
> 
> 而TV对接python后端这块的实现和资料比较少；还没弄懂可以怎么搞，好像也是要部署一个本地化的TV SDK？

不一定非要上TV，具体还是根据你的需求来选择，比如我自己的代码现在是直接用C语言模块套python直接在通达信的交易软件上跑，做辅助交易分析，你也可以通过转化API直接用图表类型的平台呈现，关键是看你都需要什么。

**Comment by Vespa314** [comment]
> > 
> 
> > > 听说有个TradingView相当好用， 你可以试试
> > 
> > 
> > 嗯，这个我知道；能上TV当然是个不错的选择；
> > 但是我自己下游有太多自定义的模型和交易相关的操作了，所以后端选择python自己开发自由度比较大；
> > python开发的代码转到TV上，代码的迁移成本无异于重做；
> > 而TV对接python后端这块的实现和资料比较少；还没弄懂可以怎么搞，好像也是要部署一个本地化的TV SDK？
> 
> 不一定非要上TV，具体还是根据你的需求来选择，比如我自己的代码现在是直接用C语言模块套python直接在通达信的交易软件上跑，做辅助交易分析，你也可以通过转化API直接用图表类型的平台呈现，关键是看你都需要什么。

是的，我自己个人使用，除了调试需要画图，其实整个交易流程都是纯后端自动化运行的，对这块没啥需求；

主要是有些朋友反馈人工判断买卖点如果有更好用的可视化的方案，会更方便。

**Comment by topsoftbj** [comment]
> > > > 听说有个TradingView相当好用， 你可以试试
> > > 
> > > 
> > > 嗯，这个我知道；能上TV当然是个不错的选择；
> > > 但是我自己下游有太多自定义的模型和交易相关的操作了，所以后端选择python自己开发自由度比较大；
> > > python开发的代码转到TV上，代码的迁移成本无异于重做；
> > > 而TV对接python后端这块的实现和资料比较少；还没弄懂可以怎么搞，好像也是要部署一个本地化的TV SDK？
> > 
> > 
> > 不一定非要上TV，具体还是根据你的需求来选择，比如我自己的代码现在是直接用C语言模块套python直接在通达信的交易软件上跑，做辅助交易分析，你也可以通过转化API直接用图表类型的平台呈现，关键是看你都需要什么。
> 
> 是的，我自己个人使用，除了调试需要画图，其实整个交易流程都是纯后端自动化运行的，对这块没啥需求；
> 
> 主要是有些朋友反馈人工判断买卖点如果有更好用的可视化的方案，会更方便。

我看了下TV提供的方案，3档服务，免费开源的是提供图表辅助，只是看的话应该够用了，很简单，web上有什么需要支持的我可以帮你，看了你的设计挺有意思的，有机会可以交流下，我等下发个联系方式到你gmail邮箱。

**Comment by DZG-MELODY** [comment]
我可以参与开发web端
