### ISSUE TITLE
如何获取完整版？

### ISSUE THREAD

**Issue by USTCma** [Vespa314/chan.py#17]

**Comment by Vespa314** [comment]
就目前收到的反馈而言，公开版已经足够大部分用户使用了；

完整版剩余部分涉及太多定制化的东西了，并没有做得那么通用；
而且使用上手难度比较高，配置也比较复杂；

可以先尝试熟悉公开版这些缠论通用的模块使用方法；

**Comment by USTCma** [comment]
可以私下share吗？想对比一下公开版有哪些不同，以及你的实现思路。谢谢～

**Comment by USTCma** [comment]
> 就目前收到的反馈而言，公开版已经足够大部分用户使用了；
> 
> 完整版剩余部分涉及太多定制化的东西了，并没有做得那么通用； 而且使用上手难度比较高，配置也比较复杂；
> 
> 可以先尝试熟悉公开版这些缠论通用的模块使用方法；

可以私下share吗？想对比一下公开版有哪些不同，以及你的实现思路。谢谢～

**Comment by Vespa314** [comment]
> > 就目前收到的反馈而言，公开版已经足够大部分用户使用了；
> > 完整版剩余部分涉及太多定制化的东西了，并没有做得那么通用； 而且使用上手难度比较高，配置也比较复杂；
> > 可以先尝试熟悉公开版这些缠论通用的模块使用方法；
> 
> 可以私下share吗？想对比一下公开版有哪些不同，以及你的实现思路。谢谢～

差异就是README里面你看到的减去公开版的：主要是特征，模型，回测，automl，交易引擎相关的脚本和环境部署配置；

思路相关的欢迎邮件与我讨论；
