### ISSUE TITLE
是否需要讨论群？

### ISSUE THREAD

**Issue by Vespa314** [Vespa314/chan.py#18]
tg？Discord？slack？不太清楚可以用科学上网的人的比例；

还是用我自建私用的mattermost？暂时不太想用微信或QQ。。

或者就用github的discussions吧？

**Comment by pizikuan** [comment]
同意，给大佬写了个邮件，请查收，谢谢

**Comment by sunyulele** [comment]
现在有讨论群了吗

**Comment by Vespa314** [comment]
> 现在有讨论群了吗

建了一个 https://t.me/zen_python ，现在没人，先用这个吧

**Comment by Vespa314** [comment]
> 大概看了一下，感谢大佬开源提供思路，如果有群了踢我一下，个人感觉discord不错，感谢！

踢；discord试了一下，有点复杂，先用tg吧。

**Comment by digger-yu** [comment]
可以建个飞书群, 可以看到历史记录,也不用翻墙
