### ISSUE TITLE
x_tick_num 没生效

### ISSUE THREAD

**Issue by Lsgo** [Vespa314/chan.py#20]
1.x_tick_num 没生效
建议:
  only_top_lv 改为需要展示的层级,比如我日线,60分钟,30分钟,我只想看30分钟.但是其实60分钟的特殊笔需要根据上一级别或者下一级别来判断.这样我list里面就有数据了.

**Comment by Vespa314** [comment]
x_tick_num没生效问题已fix；

之前设计only_top_lv的原因是早期没有支持区分各个级别的画图开关，导致父级别画了K线后子级别也要画K线，而子级别画大量稠密K线性能比较差，所以当时加了这么个开关；现在可以自由控制各个级别的图的画图元素，我理解这个开关应该没啥用；

如果真的想要绘制中间级别，可以看一下PlotDriver.py里面GetPlotMeta()，看一眼应该就知道怎么改了。

**Comment by Lsgo** [comment]
ok.我知道怎么改.谢谢.代码很有参考的价值
