### ISSUE TITLE
跨区间获取笔和线段的逻辑如何改写

### ISSUE THREAD

**Issue by Lsgo** [Vespa314/chan.py#21]
我学习的缠论需要同时获取上一级别和下一级别的笔和线段线.应该如何改写更加合理
1.本级别和次级别同笔的处理方式 本级别 当笔，次级别 当段
2.本级别不够笔，次级别够线段 本级别 当笔

**Comment by Vespa314** [comment]
线段里面有哪些笔，笔里面有哪些合并K线（即klc），klc里面有哪些独立K线（klu）这些都是可以获取得到的；

而不同级别之间的关联，唯一保证的是klu可以通过CKLine_Unit.sup_kl() 得到高一级别的klu，而高级别的klu可以通过CKLine_Unit.sub_kl_list() 来获得次级别的K线数组；

如果你想跨级别获取到笔段之间的关系，可能需要同时使用上面两部分的内容；

框架是没有保证父级别的笔的起止位置一定完全包含子级别笔的；

**Comment by Lsgo** [comment]
非常感谢给我提供了好的思路
