### ISSUE TITLE
想联系你

### ISSUE THREAD

**Issue by bandy3118** [Vespa314/chan.py#24]
老板，看了你发布的东西，很感兴趣，怎么联系你呢

**Comment by Vespa314** [comment]
你好，可以邮件联系，或者tg群里找到我。

**Comment by bandy3118** [comment]
我的邮件：bandy3118@126.com

**Comment by bandy3118** [comment]
我的微信号：35177069    昵称bandy

**Comment by Vespa314** [comment]
我的意思是，有问题可以直接发邮件给我github profile上显示的邮箱；

为了防止隐私泄露，我先帮你把你上面留的联系方式删了哈。

**Comment by bandy3118** [comment]
老板好！


看到您发布的chan.py，非常感兴趣！


由于我python刚刚入门，也是百度看到您的chan.py介绍，才开始使用GitHub（最多2、3次），所以很多规矩都不懂（让您见笑了）。


看到您在缠论方面建树颇深，描述的体系也非常完备，于是非常希望尝试自己在本地跑起来，但是就是不知道怎么入手，非常希望能够得到您的帮助。


感觉得到，您的时间也非常珍贵，如果能够得到您的帮助，我也愿意适当支付费用（见笑了）。我的微信号是35177069，希望能够添加，得到更及时的指导


谢谢您了！


bandy
















在 2023-05-30 22:42:22，"Vespa314" ***@***.***> 写道：

我的意思是，有问题可以直接发邮件给我github profile上显示的邮箱；

为了防止隐私泄露，我先帮你把你上面留的联系方式删了哈。
