### ISSUE TITLE
futu数据源获取报错

### ISSUE THREAD

**Issue by leoncuhk** [Vespa314/chan.py#25]
git下来跑README.md的demo示例代码
chan = CChan(
    code="HK.00700",
    begin_time="2012-01-01",
    end_time=None,
    data_src=DATA_SRC.FUTU,  # 数据来源,
    lv_list=[KL_TYPE.K_DAY],  # 多级别可以从大到小传入
    config=config,
    autype=AUTYPE.QFQ,
    extra_kl=None,
)
里的DATA_SRC.FUTU在Chan.py里没有定义
def GetStockAPI(src):
    _dict = {}
    if src == DATA_SRC.BAO_STOCK:
        from DataAPI.BaoStockAPI import CBaoStock
        _dict[DATA_SRC.BAO_STOCK] = CBaoStock
    if src == DATA_SRC.CCXT:
        from DataAPI.ccxt import CCXT
        _dict[DATA_SRC.CCXT] = CCXT
只有如上两个

**Comment by Vespa314** [comment]
futu数据源的方法没开放，因为需要用户自己部署futuD后端进行通信才可以运行，后端需要配置端口，账号密码，密钥啥的，比较繁琐，用户没法开箱即用；

另外futud后端不是所有数据源都可以直接获取：
- 有些数据有IP相关的约束（比如只有国内IP才可以获得A股数据）
- 有些数据源需要用户购买/升级数据源权限才可以获取；

这边建议自行部署相关的服务（参考https://openapi.futunn.com/futu-api-doc/），调通后根据quick_guide描述自行实现接入。

**Comment by leoncuhk** [comment]
感谢
