### ISSUE TITLE
交易引擎与策略类

### ISSUE THREAD

**Issue by royburns** [Vespa314/chan.py#27]
大佬，v3开发进度如何了，交易引擎与策略类这两个剥离出来了吗，有打算在v3版本开放交易引擎与策略类这两个模块吗

**Comment by Vespa314** [comment]
交易引擎没法剥离，和策略强耦合了；而且我就是用的futu的api，自行参考官方文档即可；

策略类的话参考demo_stragety，这个更容易理解和使用；

另外tg群明天会有框架使用的小分享，有兴趣的话可以加入参加；
