### ISSUE TITLE
你好.trigger_load 喂给cchan的新增k线数据如果有多区间应该怎么写

### ISSUE THREAD

**Issue by Lsgo** [Vespa314/chan.py#28]
我看回测案例中  stragety_demo2.py 的模板只有一个区间.如果是多区间
lv_list = [KL_TYPE.K_60M, KL_TYPE.K_15M, KL_TYPE.K_3M]
data_src = stockapi_cls(code, k_type = lv_list, begin_date=begin_time, end_date=end_time, autype=AUTYPE.QFQ)

如果这样写 在进行循环是会报错的 data_src.get_kl_data()
能帮写个例子吗

**Comment by Vespa314** [comment]
报啥错？

另外tg群明天会有框架使用的小分享，有兴趣的话可以加入参加；

**Comment by Lsgo** [comment]
![图片](https://github.com/Vespa314/chan.py/assets/8808422/fa3dbd1e-8a56-471a-827e-35dad84e8119)
我就改了这三个地方.  for klu in data_src.get_kl_data() 这里是不是要换别的写法,我去申请个tg账号明天可以学习

**Comment by Vespa314** [comment]
哦，不是的，每个数据类实例只负责一个级别的数据产生，所以34行应该只传一个级别的kl_type，你构造三个CBaoStock；

然后三个级别的数据取出来后，构造出三个级别的数据给trigger_load，这也是为什么trigger_load的输入是一个字典，key是级别，value是一个数组；

你看看quick_guide里面数据接入部分就理解了；
