### ISSUE TITLE
逐帧动画问题

### ISSUE THREAD

**Issue by jaycelq** [Vespa314/chan.py#33]
逐帧动画好像有问题，每帧都是新开一个窗口一闪而过，没有逐帧播放动画

**Comment by Vespa314** [comment]
有可能，我是在jupyter notebook上测的，这个功能我很少用。。

**Comment by jaycelq** [comment]
> 有可能，我是在jupyter notebook上测的，这个功能我很少用。。

嗯嗯，没关系，我在jupyter上试试看

**Comment by fanyufan** [comment]
> > 有可能，我是在jupyter notebook上测的，这个功能我很少用。。
> 
> 嗯嗯，没关系，我在jupyter上试试看

可以吗？我在jupyter notebook 中一直没有显示动画。
