### ISSUE TITLE
大佬能否开放一个SnapshotAPI的相关代码

### ISSUE THREAD

**Issue by skysunsun** [Vespa314/chan.py#34]

**Comment by Vespa314** [comment]
我自己这个是适配自己交易引擎和实盘策略所需要的结构来开发的；

拿了也不一定能直接用；需要哪一个我可以直接告诉你数据获取的方法；

**Comment by skysunsun** [comment]
根据大佬的思路，我是这样理解的，比如做15分钟，那么就是隔15分钟去取一次数据，然后喂给chan 计算，不知道这样理解对不对，如果大佬愿意给个tdx的不胜感激。

**Comment by Vespa314** [comment]
> 根据大佬的思路，我是这样理解的，比如做15分钟，那么就是隔15分钟去取一次数据，然后喂给chan 计算，不知道这样理解对不对，如果大佬愿意给个tdx的不胜感激。

嗯，你的理解是对的；

https://rainx.gitbooks.io/pytdx/content/pytdx_hq.html 参考这个即可；喂的方法参考demo里面的demo策略和quick_guide;

我那个封装的略复杂；

**Comment by skysunsun** [comment]
> > 根据大佬的思路，我是这样理解的，比如做15分钟，那么就是隔15分钟去取一次数据，然后喂给chan 计算，不知道这样理解对不对，如果大佬愿意给个tdx的不胜感激。
> 
> 嗯，你的理解是对的；
> 
> https://rainx.gitbooks.io/pytdx/content/pytdx_hq.html 参考这个即可；喂的方法参考demo里面的demo策略和quick_guide;
> 
> 我那个封装的略复杂；

谢谢大佬。
