### ISSUE TITLE
`Seg\EigenFX.py`中`can_be_end`函数存在一个逻辑错误

### ISSUE THREAD

**Issue by maelstrom-doa** [Vespa314/chan.py#36]
`can_be_end`函数的作用是判断特征序列分型是否结束，并考虑线段的两种情况：特征序列中第一和第二元素间存在特征序列的缺口。其中如果存在缺口时调用`find_revert_fx`函数寻找反向分型。  
`break_thred`参数的含义是为了判断判断特征序列缺口是否笔合，那么当线段是向上时，`break_thred`应该是`self.ele[0].high`,反向特征序列的第二个元素的低点低于此值即表明闭合，这个逻辑可以从`find_revert_fx`函数逻辑得到佐证。 
因此`break_thred = self.ele[0].low if self.is_up() else self.ele[0].high`应改为  
`break_thred = self.ele[0].high if self.is_up() else self.ele[0].low`
```python
def can_be_end(self, bi_lst: CBiList):
    """判断特征序列分型是否结束，并考虑线段的两种情况：特征序列中第一和第二元素间存在特征序列的缺口"""
    assert self.ele[1] is not None
    if self.ele[1].gap: # 第二特征序列相对第一个特征序列有缺口，线段的第二种情况
        assert self.ele[0] is not None
        end_bi_idx = self.GetPeakBiIdx()
        thred_value = bi_lst[end_bi_idx].get_end_val() #线段的端点
        break_thred = self.ele[0].low if self.is_up() else self.ele[0].high #TODO：此处写错了，break_thred值是为了判断特征序列缺口是否笔合，那么当线段是向上时，break_thred应该是self.ele[0].high
        return self.find_revert_fx(bi_lst, end_bi_idx+2, thred_value, break_thred)
    else:
        return True
```

**Comment by Vespa314** [comment]
看了一下，『break_thred参数的含义是为了判断判断特征序列缺口是否笔合』这个并不是代码的本意，而是之前在开发过程中发现一些画段badcase，会出现用特征序列计算时下降线段后面又接一段下降线段；这也是为什么CSeg的init函数最后有一个self.check()，用来检测避免因为bug出现这种状况；

回到这个问题，break_thred是因为我自己发现（跟原著无关）那些badcase，都可以通过设计一个阈值，如果egien_fx出现两个元素了，且第二元素突破前一分形这个阈值，让线段直接成立的话，这些badcase都可以避免；

这个是我仓库issue笔记的截图：
<img width="984" alt="image" src="https://github.com/Vespa314/chan.py/assets/6339395/ad309fed-ce7b-46b6-bf15-b11a1aec59b5">

<img width="899" alt="image" src="https://github.com/Vespa314/chan.py/assets/6339395/1d18d22b-0e9c-452a-a5ee-4285efb20725">
