### ISSUE TITLE
strategy_demo.py 里面的一买好像有点问题

### ISSUE THREAD

**Issue by skysunsun** [Vespa314/chan.py#37]
main.py 画图是对的，但是这个demo里面打印出来的信息是错的，比如浪潮信息，demo里面2022/9/22出了个买点，但是实际并不是，main.py画的图应该是在10月11号。
祝大佬元旦快乐。

**Comment by Vespa314** [comment]
你这个问题，容我明年再回答，哈哈哈哈。。

元旦快乐！

**Comment by Vespa314** [comment]
你要区分清楚策略在喂K线过程中产生的买卖点和绝对正确的形态学的买卖点；

demo所描述的策略会在9月22的时候产生一个开仓位置，因为在那个时候画出来的结果如下：
<img width="1177" alt="image" src="https://github.com/Vespa314/chan.py/assets/6339395/d07e3081-488d-4626-ad83-371ead137ea7">

只不过根据后续走出来的结果，9月22那个1买被跌破了，被证明不成立而已；
<img width="1168" alt="image" src="https://github.com/Vespa314/chan.py/assets/6339395/9462d722-60b4-4992-9903-b46e3c525aad">

详细介绍可以看看quick_guide[这部分](https://github.com/Vespa314/chan.py/blob/main/quick_guide.md#%E5%85%B3%E4%BA%8E%E5%BD%93%E5%89%8D%E5%B8%A7%E7%9A%84%E8%AF%A6%E7%BB%86%E8%AF%B4%E6%98%8E)；

**Comment by skysunsun** [comment]
明白了，谢谢大佬，因为我喂得K线是超过9月22的，我以为他会跟画图的那个一样。哈哈哈哈。
