### ISSUE TITLE
trigger load后bs_point_lst 未更新

### ISSUE THREAD

**Issue by handongopqwe** [Vespa314/chan.py#41]
### 代码
![image](https://github.com/Vespa314/chan.py/assets/10177597/542526ae-c822-4e1d-807d-aec55aa78fad)

### chan原始数据
![7f4c5bc0df24ed19aa8c71e5ad99e33](https://github.com/Vespa314/chan.py/assets/10177597/047eb2df-5c7b-411d-876d-73904fafd75e)
### trigger load后
![90394e968234f4bb9552baa831e2b13](https://github.com/Vespa314/chan.py/assets/10177597/1291e8af-c627-4383-b781-bdb7a703cda6)
### trigger load后调用.cal_seg_and_zs()计算
![1641c3d89dd0977b8365dd399afb008](https://github.com/Vespa314/chan.py/assets/10177597/7f547dd3-a4bb-4875-ad45-926029f4d625)

## 描述
trigger load后bi_list有更新，bs_point_lst未自动更新，需要手动调用计算函数

**Comment by quantaacc** [comment]
分支：machinelearning 
最后一次commit版本：b9ba5386 on 2024/3/16 at 15:35

**Comment by Vespa314** [comment]
可以画一下trigger前后的K线，笔，段图么？不要手动调用计算函数；

**Comment by handongopqwe** [comment]
原chan
![old](https://github.com/Vespa314/chan.py/assets/10177597/b598ade2-af4b-410a-b020-368b6601a226)

新chan
![new](https://github.com/Vespa314/chan.py/assets/10177597/20471f7b-2c38-449e-bc1c-fe222b3aa986)

新chan 计算
![new_cal](https://github.com/Vespa314/chan.py/assets/10177597/a08ab058-6e57-4ab8-ba20-37d1724d32f8)

**Comment by Vespa314** [comment]
需要打开trigger_step开关；

非 trigger_stop 模式下本来就是在CChan 的这里最后统一更新的：
<img width="766" alt="image" src="https://github.com/Vespa314/chan.py/assets/6339395/b1c773e1-bd5b-41a6-a2a3-3b6e2d55f6f3">

没考虑到有非trigger_step模式下的 trigger_load，我兼容下；
