### ISSUE TITLE
建议在KLine.KLine_List.CKLine_List类中增加原始原始K类列表类

### ISSUE THREAD

**Issue by Mjzs12138** [Vespa314/chan.py#48]
如果需要从snapshot获取原始K线序列进行一些计算（例如计算技术指标），似乎只能通过在KLine.KLine_List.CKLine_List中层层循环获取原始K线属性，效率很低。

**Comment by Vespa314** [comment]
参考https://github.com/Vespa314/chan.py/blob/main/KLine/KLine_List.py#L131，有个直接获取klu 的迭代器klu_iter()

**Comment by Mjzs12138** [comment]
谢谢！已解决
