### ISSUE TITLE
CBi.Cal_MACD_slope的计算似乎有问题

### ISSUE THREAD

**Issue by Mjzs12138** [Vespa314/chan.py#50]
计算这个指标的时候，似乎没有必要除以 end_klu.high 或 begin_klu.high。而且这么做了之后该指标的值会可能变得非常小（可能小于0.0001）
    def Cal_MACD_slope(self):
        begin_klu = self.get_begin_klu()
        end_klu = self.get_end_klu()
        if self.is_up():
            return (end_klu.high - begin_klu.low)/end_klu.high/(end_klu.idx - begin_klu.idx + 1)
        else:
            return (begin_klu.high - end_klu.low)/begin_klu.high/(end_klu.idx - begin_klu.idx + 1)

**Comment by Vespa314** [comment]
为了归一化，让指标对所有股票分布尽量一直。

指标小无所谓，不是给人看的，为的是两笔的这个指标相除算背驰度，除完就正常了。

**Comment by Mjzs12138** [comment]
了解，谢谢
