### ISSUE TITLE
BI.parent_seg数据似乎有点问题，求解

### ISSUE THREAD

**Issue by AlexYY0** [Vespa314/chan.py#51]
现在总共有4 seg
![image](https://github.com/Vespa314/chan.py/assets/32156135/a914d2b1-ded8-42b5-9d6c-c10094c6e844)
最后一段的end bi是21
![image](https://github.com/Vespa314/chan.py/assets/32156135/a4fd03c1-f61d-418e-9c80-31876c3c8322)
现在总共有24 bi
![image](https://github.com/Vespa314/chan.py/assets/32156135/7129be1b-9cd1-461b-96ad-bc4e838a5224)
bi_list的21 bi还对应的上seg，是3，且seg.next is None
![image](https://github.com/Vespa314/chan.py/assets/32156135/63502780-5c35-40b7-8ae8-ecd9475ed9c9)
但是22 bi的seg_idx 是4，这个可以理解，但是parent_seg那里来的
![image](https://github.com/Vespa314/chan.py/assets/32156135/f66690cf-2a76-4b55-b2bf-3e6f4ebdddae)
而且4 seg pre -> 3 seg，但是3 seg  next -> 竟然有了，是 4 seg，有点奇怪
![image](https://github.com/Vespa314/chan.py/assets/32156135/07be2976-8694-49cd-8eb8-da2495b7f1e6)
而到了23 bi，seg_idx 也是4，但是parent_seg就为 None了，没有了
![image](https://github.com/Vespa314/chan.py/assets/32156135/724dc1c7-f076-421a-b9e8-41c060d144db)

请问这是什么原因，因为left_seg_method配置吗，感觉悬空出来一个seg，对应不上号

**Comment by AlexYY0** [comment]
断点地方为 计算买卖点的类，所以我bsg_bi取seg出现了问题，理论上这时候都计算完了，数据应该一致才对？请问大佬这是哪里的问题 @Vespa314

**Comment by Vespa314** [comment]
方便补个带bi_num的画图么？
或者提供一下可以复现的main.py和数据源类

**Comment by AlexYY0** [comment]
> 方便补个带bi_num的画图么？ 或者提供一下可以复现的main.py和数据源类

数据是从我数据里取的，暂时不太好提供，标的是510300.SH. 30m  开始时间2012.05.25，大佬有其他数据源可以看看，图的话我晚上看看

**Comment by AlexYY0** [comment]
> 方便补个带bi_num的画图么？ 或者提供一下可以复现的main.py和数据源类

![image](https://github.com/Vespa314/chan.py/assets/32156135/e52755a2-e7ee-4859-b3a0-bbe1a70553e3)

**Comment by Vespa314** [comment]
按照设计，（根据画出来的图）如果一笔没有对应的线段，那么 parent_seg 应该是 None，但是 seg_idx 的值等于最后一根线段+1；

我没数据复现你上面的结果（我可以花时间找找，但是懒了），但是我大概猜到问题了，你可以拉一下 fix_0706这个分支，看看还会不会有问题，如果还有，麻烦提供下数据的 CSV 文件和你的 CChanConfig，我再排查下。

如果没问题，我就合进主分支了。

**Comment by AlexYY0** [comment]
> 按照设计，（根据画出来的图）如果一笔没有对应的线段，那么 parent_seg 应该是 None，但是 seg_idx 的值等于最后一根线段+1；
> 
> 我没数据复现你上面的结果（我可以花时间找找，但是懒了），但是我大概猜到问题了，你可以拉一下 fix_0706这个分支，看看还会不会有问题，如果还有，麻烦提供下数据的 CSV 文件和你的 CChanConfig，我再排查下。
> 
> 如果没问题，我就合进主分支了。

这是数据文件，fix_0706这个分支我还没有测试，晚点看看
[stock_data.xlsx](https://github.com/user-attachments/files/16116754/stock_data.xlsx)

**Comment by Vespa314** [comment]
嗯，测了一下，fix_0706已经修复这个问题了，主分支代码已更新。

**Comment by AlexYY0** [comment]
> 嗯，测了一下，fix_0706已经修复这个问题了，主分支代码已更新。

请问程序什么情况下一笔会没有对应的线段，我看collect_left_seg_peak_method的collect_left_as_seg方法，以为最多会存在一笔没有线段，现在看好像不是这样?

**Comment by Vespa314** [comment]
最多出现在尾部的两笔

**Comment by AlexYY0** [comment]
> 最多出现在尾部的两笔

left_seg_method这个配置不会处理这些这两笔吗，还是说处理后剩下的不确定笔

**Comment by Vespa314** [comment]
有些情况下不会。

**Comment by AlexYY0** [comment]
> 嗯，测了一下，fix_0706已经修复这个问题了，主分支代码已更新。

感谢V神，试了一下，确实已经没问题了

**Comment by AlexYY0** [comment]
> 有些情况下不会。

好的，大概了解了，感谢
