### ISSUE TITLE
ZS.ZS.out_bi_is_peak除零错误

### ISSUE THREAD

**Issue by Mjzs12138** [Vespa314/chan.py#52]
该函数有一定几率可能触发该错误

  File "/home/mjzs/.local/lib/python3.10/site-packages/cchan/ZS/ZS.py", line 211, in out_bi_is_peak
    r = abs(bi.get_end_val()-self.bi_out.get_end_val())/self.bi_out.get_end_val()
ZeroDivisionError: float division by zero

**Comment by Vespa314** [comment]
这个是因为有股票的最低价触达0了？
