### ISSUE TITLE
Bi.next未重置的问题

### ISSUE THREAD

**Issue by AlexYY0** [Vespa314/chan.py#55]
如图所示，bi_list总共有67笔
![image](https://github.com/Vespa314/chan.py/assets/32156135/77fc2c3a-7552-4841-a7b0-e0b18030eb0f)
但是第最后一笔的next竟然还有值，是不是哪里没有重置的问题
![image](https://github.com/Vespa314/chan.py/assets/32156135/d5c4c080-5c20-4fee-843c-4fed4bfe5c70)

**Comment by AlexYY0** [comment]
而且时间区间感觉也z不应该在那里
![image](https://github.com/Vespa314/chan.py/assets/32156135/f9f8c20a-d621-4ad0-9b31-88cf3d3f3afd)

**Comment by Vespa314** [comment]
和#51 应该是类似的问题和修复方法，拉一下新代码再试试。

**Comment by ivyfeng0702** [comment]
想请教一下 @AlexYY0 ，这里用的是什么工具？感觉你这个看变量还蛮好用的

**Comment by AlexYY0** [comment]
> 想请教一下 @AlexYY0 ，这里用的是什么工具？感觉你这个看变量还蛮好用的

[PyCharm](https://www.jetbrains.com/pycharm/)

**Comment by AlexYY0** [comment]
> 和#51 应该是类似的问题和修复方法，拉一下新代码再试试。

我的assert没有报错，应该是已经修复了
