### ISSUE TITLE
Seg添加@make_cache

### ISSUE THREAD

**Issue by AlexYY0** [Vespa314/chan.py#57]
能否让Seg也具有@make_cache缓存计算结果的能力呢？因为我在Seg内部写了一些特征计算。我这边加了，但是不确定什么时候clean_cache，只能怀疑是内部元素变动时候，不确定加的是否正确，应该是这些方法结束时需要clean：add_zs、update_bi_list，不确定set_seg_idx后是否需要clean
`
    def clean_cache(self):
        self._memoize_cache = {}
`

**Comment by Vespa314** [comment]
seg 我忘了为啥不加 cache 了，年代太久远了，大概率原因就是容易出 bug。

**Comment by AlexYY0** [comment]
> seg 我忘了为啥不加 cache 了，年代太久远了，大概率原因就是容易出 bug。

好吧，本来想说参考其他的自己加的，看起来行不通了
