### ISSUE TITLE
关于CKLine与Bi之间的关联

### ISSUE THREAD

**Issue by AlexYY0** [Vespa314/chan.py#61]
请问CKLine和Bi应该怎么串联起来，尤其是使用区间套的时候，CKLine_Unit有sub_kl_list和sup_kl，有了次级别klu或更高级别klu，但是却无法直接得出Bi，难道要遍历所有的Bi? 还有我发现CKLine_Unit的kl_type是空的，这种情况下，得到了K线，怎么确定是哪一级别，怎么遍历对应的级别的bi呢。

**Comment by Vespa314** [comment]
klc没有直接获得笔的方法，考虑到的是笔首尾两端的 klc 可能属于前后两笔，所以这块交由你们自己逻辑判断（通过遍历的方法），或者自行改造 CBi。

kl_type为空怎么复现？照理来说 https://github.com/Vespa314/chan.py/blob/main/Chan.py#L91 都已经设置了的。

**Comment by AlexYY0** [comment]
> klc没有直接获得笔的方法，考虑到的是笔首尾两端的 klc 可能属于前后两笔，所以这块交由你们自己逻辑判断（通过遍历的方法），或者自行改造 CBi。
> 
> kl_type为空怎么复现？照理来说 https://github.com/Vespa314/chan.py/blob/main/Chan.py#L91 都已经设置了的。

好的，我大概清楚了，谢谢大佬，看来还是得遍历所有得笔。
https://github.com/Vespa314/chan.py/blob/main/Chan.py#L91这种只适用于预先加载所有数据得情况，比如step_load()，但是trigger_load()就不行了，只能自己操作，我看demo里应该都是没有的

**Comment by Vespa314** [comment]
kl_type丢失问题已修复。
