### ISSUE TITLE
多级别的时候，Copy这种方式速度慢的吓人，有其他的解决方法吗

### ISSUE THREAD

**Issue by AlexYY0** [Vespa314/chan.py#64]
如题
trigger_load的时候，如果涉及到多级别，使用copy速度慢的吓人，有其他的解决方案吗？
![image](https://github.com/user-attachments/assets/9a3bc7a8-57dc-41e7-bc9e-18ef15d89a13)
如果只能用Copy的话，感觉多级别用不起来

**Comment by Vespa314** [comment]
python 的性能上限确实不会特别高。

你的最小基本是秒级别的？

**Comment by AlexYY0** [comment]
> python 的性能上限确实不会特别高。
> 
> 你的最小基本是秒级别的？

不是，是5m和30m
那这种情况是不是用不了了。只能30m执行一次，5m的数据先存在，最后一次性feed

**Comment by Vespa314** [comment]
没太懂你的问题在哪里。

**Comment by AlexYY0** [comment]
> 没太懂你的问题在哪里。

就是除了copy的方式使用多级别，实盘的时候还有其他的方式使用多级别吗，因为copy实在太慢了

**Comment by royinn** [comment]
我遇到问题是15m级别，跑几年数据一开始挺快，几年后就开始非常慢
