### ISSUE TITLE
用csvapi生成时候 标的是XAUUSD 周期是30min 会出现CChanException异常

### ISSUE THREAD

**Issue by bthuntergg** [Vespa314/chan.py#68]
File "D:\pythonProject\vnpyB\chan.py-main\Chan.py", line 247, in load_iterator
    raise CChanException(f"kline time err, cur={kline_unit.time}, last={self.klu_last_t[lv_idx]}", ErrCode.KL_NOT_MONOTONOUS)
Common.ChanException.CChanException: kline time err, cur=2020/01/01 00:30, last=2020/01/01

原因是对天的自动理解 
只能将auto 设置位False解决

**Comment by Vespa314** [comment]
嗯，[这里](https://github.com/Vespa314/chan.py/blob/main/quick_guide.md#%E6%8A%A5k%E7%BA%BF%E6%97%B6%E9%97%B4%E7%9B%B8%E5%85%B3%E9%94%99%E8%AF%AF)说明了。
