### ISSUE TITLE
您好，能不能大体说一下接下来的计划，或者没计划也行，目前文档写了一大堆，让人觉得是完整的，但实际文件还缺很多

### ISSUE THREAD

**Issue by dfengwin** [Vespa314/chan.py#8]

**Comment by Vespa314** [comment]
当前公开版的框架已经可以用于开发一些自定义策略了；

完整版还在迭代开发中，涉及到的东西比较多，不熟的人使用问题会很多，解答起来也比较麻烦，所以暂时没有具体公开的精确时间；

公开版如有问题和意见，欢迎讨论；
